name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          🎉 Welcome to our repository! 🎉

          Thank you for opening your first issue. We’re excited to have you here and appreciate your contribution. Our team will look into this shortly.

          In the meantime, feel free to check out our contributing guide or reach out if you have any questions. Let's collaborate and make something great together! 💡

          Happy coding! 🚀
          
        pr-message: |
          🎉 Congratulations on your first pull request! 🎉

          Thank you for contributing to our project. We appreciate the effort you’ve put into this! Our team will review your changes shortly.

          Feel free to check out our contributing guide for more info on how we collaborate here. We’re excited to work together and make this project even better! 💡

          Thanks again, and happy coding! 🚀
